project:
  type: book

book:
  title: "PhD Oriane"
  author: "Oriane Braud"
  date: "04/11/2024"
  chapters:
    - index.qmd
    - abstract.qmd
    - intro.qmd
    - part: year_1.qmd
      chapters:
      - structural_cereal_model.ipynb
      - dynamic_model.ipynb
    - part: year_2.qmd
    - part: year_3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo


# execute:
#   freeze: auto


