from __future__ import annotations

from .archicrop import ArchiCrop
from .stand import agronomic_plot

class ArchiCropScene:

    def __init__(self, sowing_density, inter_row, length_plot, width_plot):
        """
        Initialize a stand of plants generated by ArchiCrop model.

        :param sowing_density: float, sowing density (plants/m²)
        :param inter_row: float, distance between rows (...)
        :param length_plot: float, length of the plot (in m)
        :param width_plot: float, width of the plot (in m)
        """
        self.sowing_density = sowing_density
        self.inter_row = inter_row
        self.length_plot = length_plot
        self.width_plot = width_plot
        